version: '3'

tasks:
  test:
    desc: Run all tests
    deps: [build]
    aliases: [t]
    cmds:
      - go test -v ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  templ:
    internal: true
    cmds:
      - templ generate

  tailwind:
    internal: true
    cmds:
      - npx tailwindcss -i ./internal/app/web/tailwind.css -o ./internal/app/web/static/output.css

  build:
    desc: Build all executables
    deps: [templ, tailwind]
    aliases: [b]
    cmds:
      - go build -v -o bin/web cmd/web/main.go

  clean:
    desc: Clean project
    cmds:
      - go clean
      - rm -rf bin/

  "run:web":
    desc: Run webserver
    deps: [build]
    aliases: [rw]
    cmds:
      - air

  fmt:
    desc: Format go code
    cmds:
      - gofmt -l -s -w .

  fmtcheck:
    desc: Check if the go code is formatted
    cmds:
      - gofmt -l -s .
