name: Go CI

on:
  push:
    branches:
      - "**"

# don't waste CI time by cancelling previous workflow on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: "1.23"
  GO_TASK_VERSION: "v3.39.2"
  GO_TEMPL_VERSION: "v0.2.778"
  GO_CI_LINT_VERSION: "v1.61"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./ci/install_tools.sh ${{ env.GO_VERSION }} ${{ env.GO_TASK_VERSION }} ${{ env.GO_TEMPL_VERSION }}
      - run: echo "$HOME/go/bin" >> "$GITHUB_PATH"
        # project must be built to generate templ files,
        # otherwise the linter will report an issue about
        # unexisting symbols in package 'views'
      - run: task build
      - uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GO_CI_LINT_VERSION }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./ci/install_tools.sh ${{ env.GO_VERSION }} ${{ env.GO_TASK_VERSION }} ${{ env.GO_TEMPL_VERSION }}
      - run: echo "$HOME/go/bin" >> "$GITHUB_PATH"
      - run: task test

  fmtcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./ci/install_tools.sh ${{ env.GO_VERSION }} ${{ env.GO_TASK_VERSION }} ${{ env.GO_TEMPL_VERSION }}
      - run: echo "$HOME/go/bin" >> "$GITHUB_PATH"
      - name: check go code format
        shell: bash
        run: | 
          [ $(task fmtcheck | wc -l) -eq 0 ] && exit 0 || exit 1
